dudalibrary/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/add_custom/$',
        'frontend.views.add_custom',
        name='add_custom_resource_url'),
    url(r'^admin/enqueue_resources/$',
        'frontend.views.admin_enqueue_resources',
        name='admin_enqueue_resources'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',),
    
)

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

admin.autodiscover()

urlpatterns += patterns('',
    url(r'^$', 'frontend.views.index', name='index'),
    url(r'^i18n/', 'frontend.views.set_language', name='set_language'),    
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        name='auth_logout'),    
    )

urlpatterns += i18n_patterns('',
    url(_(r'^random/$'), 'frontend.views.get_random_resource', name='get_random_resource_url'),
    url(_(r'^activity/(?P<object_id>\d+)/$'), 'frontend.views.activity_details', name="activity_details"),
    url(_(r'^curricular/(?P<curricular_id>\d+)/class/(?P<class_id>\d+)/activity/select_subject/'), 'frontend.views.curricular_activity_select_add_subject', name="curricular_activity_select_add_subject"),
    url(_(r'^curricular/(?P<curricular_id>\d+)/class/(?P<class_id>\d+)/subject/(?P<subject_id>\d+)/activity/add/'), 'frontend.views.curricular_add_activity', name="curricular_add_activity"),
    url(_(r'^curricular/(?P<object_id>\d+)/'), 'frontend.views.get_curricular_grade', name="curricular_grade"),
    url(_(r'^resource/tag/(?P<pk>[^/]+)/$'), 'frontend.views.tag_details', name="tag_details"),
    url(_(r'^resource/(?P<object_id>\d+)/'), 'frontend.views.resource_details', name="resource_details"),
    url(_(r'^source/(?P<object_id>\d+)/'), 'frontend.views.source_details', name="source_details"),
    url(_(r'^source/points.txt$'), 'frontend.views.source_points', name="source_points"),
    url(r'^search/', include('haystack.urls'))
)

if settings.DEBUG:
    urlpatterns += patterns('',
    # CONTENT MEDIA
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

        (r'^content/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.CONTENT_ROOT, 'show_indexes': True }),
    )
    

curricular/models.py
import datetime

from options.models import Language
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
import tagging
from tagging.fields import TagField
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class CurricularGrade(models.Model):

    def __unicode__(self):
        if not self.parent:
            return u'%s' % self.title
        else:
            return u'%s - %s' % (self.parent, self.title)

    parent = models.ForeignKey('self', blank=True, null=True, limit_choices_to = {'parent': None})
    title = models.CharField(blank=False, null=False, max_length=100)
    description = models.TextField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class SubjectClass(models.Model):
    '''1 Serie, 2 Serie, etc'''

    def __unicode__(self):
        return u'%s' % self.title
    
    curricular_grade = models.ForeignKey(CurricularGrade)
    title = models.CharField(_("Title"), blank=False, null=False, max_length=100)
    description = models.TextField(_("Description"), blank=True)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class Subject(models.Model):
    
    def __unicode__(self):
        #return u'%s (%s)' % (self.title, self.subject_class.title)
        return u'%s' % self.title
    
    class Meta:
        ordering = ['title']

    title = models.CharField(blank=False, null=False, max_length=100)
    subject_class = models.ForeignKey(SubjectClass)
    description = models.TextField(blank=True)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class ActivityItem(models.Model):

    def __unicode__(self):
        try:
            output = u'%s (%s)' % (self.item.title, self.content_type)
        except:
            output = u'%s' % self.item
        return output

    class Meta:
        unique_together = (('activity', 'order'),)

    '''Relative to an Exercise or Resource'''
    order = models.IntegerField(blank=False, null=False)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    item = generic.GenericForeignKey('content_type', 'object_id')
    activity = models.ForeignKey('Activity')
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class Activity(models.Model):
    
    @models.permalink
    def get_absolute_url(self):
        return ('activity_details', (), 
            {
            'object_id': str(self.id),
            }
        )
    
    
    def __unicode__(self):
        return u'%s' % self.title
    
    subject = models.ForeignKey(Subject)
    title = models.CharField(blank=False, max_length=100)
    description = models.TextField(blank=True)
    tags = TagField(max_length=400)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class Exercise(models.Model):
    
    def __unicode__(self):
        return u'%s' % self.title
    
    title = models.CharField(blank=True, max_length=100)
    description = models.TextField(blank=True)
    tags = TagField(max_length=400)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)    

# tagging conf
tagging.register(Activity, tag_descriptor_attr="tag_handler")
tagging.register(Exercise, tag_descriptor_attr="tag_handler")

dudalibrary/templates/default/browse.html
{% load i18n %}
{% load highlight %}

<div id="browse">
	<h1>{% trans "Browse into knowledge" %}</h1>
        
{% if featured_list %}
    <div class="well well-small">
	{% include "featured_list.html" with object_list=featured_list %}
    </div>
{% endif %}
    
    <div class="row-fluid">

	  <div class="span12">
  			<h2>{% trans "OER World Map" %}</h2>
			<style>
			#map{
				height: 400px;
				width: 100%;
			}
			</style>
		  {% include "world-map-v2.html" %}
	  </div>
      
      
    </div><!--/row-->


    
	{% if tags_to_cloud %}
	<div id="tagcloud">
	{% regroup tags_to_cloud|dictsortreversed:"count" by count as tag_list %}
		<h2>{% trans "Tag Cloud" %}</h2>
		<p>
		{% for count in tag_list %}
			{%for tag in count.list %}
				<font size="{{ tag.font_size }}">
					{% ifequal tag.id actual_tag.id %}<b>{% endifequal %}
					<a href="{% url "tag_details" tag.id %}?q={{q}}">{{tag.name}} {# ({{count.grouper}})#}</a>
					{% ifequal tag.id actual_tag.id %}</b>{% endifequal %}
				</font>
			{% endfor %}
		{%endfor%}
		</p>
	</div>
	{% endif %}	
</div>

dudalibrary/templates/default/curricular_activity_select_add_subject.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div id="add-curricular-activity">    
    <h1>{{curricular_grade}}</h1>
    <h2>{{curricular_class}}</h2>
    {% if subjects %}
        <h4>{% trans "Use an existing Subject Class" %}</h4>
        <ul>
        {% for subject in subjects %}
        <li><a href="{% url "curricular_add_activity" curricular_grade.id curricular_class.id subject.id %}">{{subject.title}}</a></li>
        {% endfor %}
        </ul>
    {%endif %}

    {% if request.user and perms.curricular.add_subjectclass %}
    <h4>{% trans "Add a new Subject Class" %}</h4>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <p><input type="submit" class="btn btn-success" value="{% trans "Add" %}"></p>
    </form>
    {% endif %}
</div>

{% endblock %}

dudalibrary/templates/default/curricular_add_activity.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div id="add-curricular-activity">    
    <h1>{{curricular_grade}}</h1>
    <h2>{{curricular_subject}}: {{curricular_class}}</h2>
    <h4>{% trans "Add a new Activity" %}</h4>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <p><input type="submit" class="btn btn-success" value="{% trans "Add" %}"></p>
    </form>
</div>

{% endblock %}

dudalibrary/templates/default/curricular_grade_details.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div id="browse-curricular">
	
    <div id="show-activity">
        <h1>{{curricular_grade}}</h1>
        
        {% if curricular_grade.parent %}
        
        <ul class="nav nav-tabs" id="myTab">
            {% for class in curricular_grade.subjectclass_set.all %}
            <li class="{% if forloop.first %}active{%endif%}"><a href="#class-{{class.id}}" data-toggle="tab">{{class}}</a></li>
            {% endfor %}
            {% if request.user and perms.curricular.add_subjectclass %}
            <li><a href="#add-class" data-toggle="tab">{% trans "Add Class" %}</a>
                {% endif %}
            </ul>
 
            <div class="tab-content">
                {% for class in curricular_grade.subjectclass_set.all %}
                <div class="tab-pane {% if forloop.first %}active{%endif%}" id="class-{{class.id}}">
                    <p>{{class.description}}</p>
                    <h3>{{class}}</h3>
                    <hr />
                    {% for subject in class.subject_set.all %}
                        <h4><strong>{{subject}}</strong></h4>
                        <ul>
                            {% for activity in subject.activity_set.all %}
                            <li><a href="{% url "activity_details" activity.id %}">{{activity}}{% if activity.description %} - {{activity.description}}{%endif%}</a></li>
                            {% endfor %}
                            {% if request.user and perms.curricular.add_activity %}                           <a href="{% url "curricular_add_activity" curricular_grade.id class.id subject.id %}" class="btn btn-info"><i class="icon icon-plus icon-white"></i> {% blocktrans %}Add Activity at {{subject}} Subject{% endblocktrans %}</a>
                            {% endif %}

                        </ul>
                        <hr />    
                    {% endfor %}

                    {% if request.user and perms.curricular.add_activity %}
                    <hr />
                    <a class="btn btn-success" href="{% url "curricular_activity_select_add_subject" curricular_grade.id class.id %}"><i class="icon-white icon-plus"></i> {% trans "Add Activities" %}</a>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="tab-pane" id="add-class">
                    <h2>{% trans "Add a new Class" %}</h2>
                    <form method="POST">
                        {% csrf_token %}
                        {{add_curricular_class_form}}
                        <p><input type="submit" class="btn btn-success" value="{% trans 'Add' %}"></p>
                    </form>
                </div>
            </div>
 
            <script>
                $(function () {
                    $('#myTab a:first').tab('show');
                })
                $('#myTab a').click(function (e) {
                    e.preventDefault();
                    $(this).tab('show');
                })
            </script>

            {% else %}
            <ul>
                {% for curricular_child in curricular_grade.curriculargrade_set.all %}
                <li><a href="{% url "curricular_grade" curricular_child.id %}">{{curricular_child}}</a></li>
                {% endfor %}
            </ul>
        
            {% endif %}

        </div>
    </div>

    {% endblock %}

dudalibrary/templates/default/index.html
{% extends 'base.html' %}
{% load i18n %}
{% url "search" as url_search %}
{% load highlight %}

{% block content %}

{% if query or blankquery %}
	{% include "resources_object_list.html" %}
	{% include "paginator.html" %}
{% else %}
	{% include "browse.html" %}
{% endif %}

{% endblock %}

dudalibrary/templates/default/languages.html
{% load i18n %}
<div id="languages">
    <h2>{% trans "Language" %}</h2>
    <form action="{% url "set_language" %}" method="get" class="input-append">
    <input name="next" type="hidden" value="{{ request.get_full_path }}" />
    <select name="language">
    {% get_language_info_list for LANGUAGES as languages %}
    {% for language in languages %}
    <option value="{{ language.code }}"{% ifequal language.code request.LANGUAGE_CODE %}selected="yes"				                {% endifequal %}>{{ language.name_local|capfirst }} ({{ language.code }})</option>
    {% endfor %}
    </select>
    <input type="submit" value="{% trans "Go" %}" class="btn"/>
    </form>
</div>

dudalibrary/templates/default/sidebar.html
{% load i18n %}
{#### SIDEBAR ####}
{% if resource %}
{% include "resource_sidebar.html" %}
{% endif %}

<div id="searchbox" style="text-align:center; margin-bottom: 20px">
    <h4>{% trans "Search" %}</h4>
    <form method="get" action="{% url "haystack_search" %}" id="search_box" class="form-search">
        <input type="text" name="q" class="input-medium search-query" value={% if query %}{{query}}{% endif %}>
		<button type="submit" class="btn">{% trans "Go" %}</button>
    </form>
</div>

{% if curricular_grades %}
<div id="curricular-grades">
	<h2>{% trans "Curricular Grades" %}</h2>
	<ul>
	{% for curricular in curricular_grades %}
		<li><a href="{% url "curricular_grade" curricular.id %}">{{curricular}}</a></li>
	{% endfor %}
	</ul>
</div>
{% endif %}

{% if select_detailed_source %}
<h2>OER Sources {{source_points.count}}</h2>
{{select_detailed_source}}
<hr />
<a href="" class="btn btn-primary"><i class="icon icon-plus icon-white"></i> Suggest a New OER Source.</a>
{% endif %}

dudalibrary/templates/default/source_details.html
{% extends "base.html" %}
{% load i18n %}
{% load highlight %}
{% block content %}
{% load tagging_tags %}

<script type="text/javascript">
    $(document).ready(function() {
    });
</script>
<div id="show-source">
	<div class="row-fluid">
		
		<div class="span8">
			
			<div div="source title">
				<h1>
					{{ source.name}}
				</h1>
				{% if source.logo %}
				<p><a href="{{source.url}}"><img src="{{source.logo.url}}"></a></p>
				{% else %}
				<a class="btn btn-info" href="{{source.url}}"><i class="icon icon-share-alt icon-white"></i> Visit this source</a>
				{% endif %}
			</div>
			
			
		</div>
		
		<div class="span4">
			<a href="{{source.url}}" class="btn btn-info">Visit this Source <i class="icon icon-arrow-right icon-white"></i></a>
		</div>
		
	</div>
		
	<div class="row-fluid">

		<div class="span6">	
						
				<style>
				#map{
					height: 230px;
					width: 100%;
				}
				</style>

				
				{% include "world-map.html" %}
				
			</div>
		
		<div class="span6">
				<div id="related-sources" class="well well-small">
				<h2>Related Sources</h2>
				<ul>
				{% for source in related_sources %}
					<li><a href="{% url "source_details" source.id %}">{{source}}</a></li>
				{% endfor %}
				</ul>
				</div>
		
				{% tags_for_object source as tag_list  %}
				{% if tag_list %}
				<div id="tags" class="well well-small">
				<h2>{% trans "Related Tags" %}</h2>
					{% for tag in tag_list %}
						<a href="{% url "tag_details" tag.id %}">{{tag.name}}</a>{% if not forloop.last %},{%endif %}
					{% endfor %}
				</div>
				{% endif %}
				
				
			</div>
		
	</div>
		
		<h1>Indexed Open Educational Resources</h1>
		
		{% regroup resources_form_source by main_category as resource_by_category %}
		
		<!-- Nav tabs -->
		<ul class="nav nav-tabs">
			{% for list in 	resource_by_category %}
		  <li class="{% if forloop.first%}active{%endif%}"><a href="#contents-{{list.grouper|lower}}" data-toggle="tab">{{list.grouper}} ({{list.list|length}})</a></li>
			  {% endfor %}
		</ul>

		<!-- Tab panes -->
		<div class="tab-content">
			{% for list in resource_by_category %}
					<div class="tab-pane {% if forloop.first%}active{%endif%}" id="contents-{{list.grouper|lower}}">
						<ul>
						{% for resource in list.list %}
							<li><a href="{% url "resource_details" resource.id %}">{{resource.title}}</a></li>
						{% endfor %}
						</ul>
					
					</div>
			{% endfor %}
		  
		</div>
		
</div>

{% endblock %}

dudalibrary/templates/default/source_points.html
lat	lon	title	description	icon	iconSize	iconOffset{% for source in source_points %}
{{source.point.x}}	{{source.point.y}}	{{source.name}}	Ol_icon_red_example.png	16,16	-8,-8{% endfor%}

dudalibrary/templates/default/tophit_list.html
{% extends 'base.html' %}
{% load i18n %}
{% url "search" as url_search %}
{% load highlight %}

{% block content %}
	<h1>{% trans "Top Viewed" %}</h1>
	<h2>{% blocktrans with page_obj.number as page %}Page {{page}} {% endblocktrans %}</h2>
	<div id="browse">
		<div id="toplists">	
		{% include "tophit_list_items.html" %}
		{% include "paginator.html" %}
		</div>
		
		<div id="featuredlist">
			<h2>Featured Resource</h2>
			{% include "featured_list.html" with object_list=featured_list %}
		</div>
	</div>
{% endblock %}

dudalibrary/templates/default/tophit_list_items.html
{% load i18n %}
<ul>
    <h2>{% trans "Top Viewed" %}</h2>        
	{% for resource in object_list %}
        {% if resource.content_object.enabled %}

		{% url "resource_details" resource.content_object.id  as url_resource %}
		<li><a href="{{url_resource}}"><span class="item_attribute">{{resource.hits}}</span>{{ resource }}</a></li>        
        {% endif %}
	{% endfor %}
    <p><a class="btn" href="">{% trans "see the entire list  &raquo;" %}</a></p>
    
</ul>

dudalibrary/templates/default/topvoted_list.html
{% extends 'base.html' %}
{% load i18n %}
{% url "search" as url_search %}
{% load highlight %}

{% block content %}
	<h1>{% trans "Top Voted" %}</h1>
	<h2>{% blocktrans with page_obj.number as page %}Page {{page}} {% endblocktrans %}</h2>
	<div id="browse">
		<div id="toplists">	
		{% include "topvoted_list_items.html" %}
		{% include "paginator.html" %}
		</div>
		
		<div id="featuredlist">
			<h2>Featured Resource</h2>
			{% include "featured_list.html" with object_list=featured_list %}
		</div>
	</div>
{% endblock %}

dudalibrary/templates/default/topvoted_list_items.html
{% load i18n %}
<ul>
{% for resource in object_list %}
	{% if resource.average %}
		<li><a href="{% url "resource_details" resource.id %}"><span class="resource-score">{{resource.average}}</span> {{resource.title}}, <i>

{% blocktrans count num_votes=resource.num_votes %}with {{num_votes}} vote{% plural %}with {{num_votes}} votes{% endblocktrans %}
			</i>
			</a></li>
	{% endif %}
{% endfor %}
</ul>

dudalibrary/templates/default/world-map.html
<div id="map"></div>
<script src="http://maps.google.com/maps/api/js?v=3&amp;sensor=false"></script>
<script src="http://openlayers.org/api/OpenLayers.js"></script>

<script>
  map = new OpenLayers.Map("map");
  map.addLayer(new OpenLayers.Layer.Google());
  
  epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
  projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)
 
  {% if source_points|length == 1 %}
  
	center = new OpenLayers.LonLat({{source_points.0.point.x}}, {{source_points.0.point.y}}).transform(epsg4326, projectTo);
	map.setCenter(center, 3);
  
  {% else %}

	center = new OpenLayers.LonLat(273950.30933588, 2230738.2331641)
	map.setCenter(center, 2);
  
  {% endif %}
	

  var vectorLayer = new OpenLayers.Layer.Vector("Overlay");
  
  {% for source in source_points %}
  var feature = new OpenLayers.Feature.Vector(
          new OpenLayers.Geometry.Point( {{source.point.0}}, {{source.point.1}} ).transform(epsg4326, projectTo),
          {description:'{{source}}', url: '{% url "source_details" source.id %}', logo_url: '{% if source.logo %}{{source.logo.url}}{%endif%}'} ,
          {externalGraphic: 'http://www.openlayers.org/dev/img/marker.png', graphicHeight: 25, graphicWidth: 21, graphicXOffset:-12, graphicYOffset:-25  }
      );    
  vectorLayer.addFeatures(feature);
  {% endfor %}

  map.addLayer(vectorLayer);

  
  //Add a selector control to the vectorLayer with popup functions
  var controls = {
    selector: new OpenLayers.Control.SelectFeature(vectorLayer, { hover:false, onSelect: createPopup, onUnselect: destroyPopup })
  };
  function createPopup(feature) {
	  if (feature.attributes.logo_url){
		  html_do_popup = '<div class="markerContent"><a href="'+feature.attributes.url+'"><img src="'+feature.attributes.logo_url+'"></a></div>'
	  }else{
		  html_do_popup = '<div class="markerContent"><a href="'+feature.attributes.url+'">'+feature.attributes.description+'</a></div>'
	  }
    feature.popup = new OpenLayers.Popup.FramedCloud("pop",
        feature.geometry.getBounds().getCenterLonLat(),
        null,
        html_do_popup,
        null,
        true,
        function() { controls['selector'].unselectAll(); }
    );
    //feature.popup.closeOnMove = true;
    map.addPopup(feature.popup);
  }

  function destroyPopup(feature) {
    feature.popup.destroy();
    feature.popup = null;
  }
  
  map.addControl(controls['selector']);
  controls['selector'].activate();
    
</script>