dudalibrary/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/add_custom/$',
        'frontend.views.add_custom',
        name='add_custom_resource_url'),
    url(r'^admin/enqueue_resources/$',
        'frontend.views.admin_enqueue_resources',
        name='admin_enqueue_resources'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',),
    
)

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

admin.autodiscover()

urlpatterns += patterns('',
    url(r'^$', 'frontend.views.index', name='index'),
    url(r'^i18n/', 'frontend.views.set_language', name='set_language'),    
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        name='auth_logout'),    
    )

urlpatterns += i18n_patterns('',
    url(_(r'^random/$'), 'frontend.views.get_random_resource', name='get_random_resource_url'),
    url(_(r'^activity/(?P<object_id>\d+)/$'), 'frontend.views.activity_details', name="activity_details"),
    url(_(r'^curricular/(?P<curricular_id>\d+)/class/(?P<class_id>\d+)/activity/select_subject/'), 'frontend.views.curricular_activity_select_add_subject', name="curricular_activity_select_add_subject"),
    url(_(r'^curricular/(?P<curricular_id>\d+)/class/(?P<class_id>\d+)/subject/(?P<subject_id>\d+)/activity/add/'), 'frontend.views.curricular_add_activity', name="curricular_add_activity"),
    url(_(r'^curricular/(?P<object_id>\d+)/'), 'frontend.views.get_curricular_grade', name="curricular_grade"),
    url(_(r'^resource/tag/(?P<pk>[^/]+)/$'), 'frontend.views.tag_details', name="tag_details"),
    url(_(r'^resource/(?P<object_id>\d+)/'), 'frontend.views.resource_details', name="resource_details"),
    url(_(r'^source/(?P<object_id>\d+)/'), 'frontend.views.source_details', name="source_details"),
    url(_(r'^source/points.txt$'), 'frontend.views.source_points', name="source_points"),
    url(r'^search/', include('haystack.urls'))
)

if settings.DEBUG:
    urlpatterns += patterns('',
    # CONTENT MEDIA
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

        (r'^content/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.CONTENT_ROOT, 'show_indexes': True }),
    )
    

curricular/models.py
import datetime

from options.models import Language
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
import tagging
from tagging.fields import TagField
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class CurricularGrade(models.Model):

    def __unicode__(self):
        if not self.parent:
            return u'%s' % self.title
        else:
            return u'%s - %s' % (self.parent, self.title)

    parent = models.ForeignKey('self', blank=True, null=True, limit_choices_to = {'parent': None})
    title = models.CharField(blank=False, null=False, max_length=100)
    description = models.TextField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class SubjectClass(models.Model):
    '''1 Serie, 2 Serie, etc'''

    def __unicode__(self):
        return u'%s' % self.title
    
    curricular_grade = models.ForeignKey(CurricularGrade)
    title = models.CharField(_("Title"), blank=False, null=False, max_length=100)
    description = models.TextField(_("Description"), blank=True)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class Subject(models.Model):
    
    def __unicode__(self):
        #return u'%s (%s)' % (self.title, self.subject_class.title)
        return u'%s' % self.title
    
    class Meta:
        ordering = ['title']

    title = models.CharField(blank=False, null=False, max_length=100)
    subject_class = models.ForeignKey(SubjectClass)
    description = models.TextField(blank=True)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class ActivityItem(models.Model):

    def __unicode__(self):
        try:
            output = u'%s (%s)' % (self.item.title, self.content_type)
        except:
            output = u'%s' % self.item
        return output

    class Meta:
        unique_together = (('activity', 'order'),)

    '''Relative to an Exercise or Resource'''
    order = models.IntegerField(blank=False, null=False)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    item = generic.GenericForeignKey('content_type', 'object_id')
    activity = models.ForeignKey('Activity')
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class Activity(models.Model):
    
    @models.permalink
    def get_absolute_url(self):
        return ('activity_details', (), 
            {
            'object_id': str(self.id),
            }
        )
    
    
    def __unicode__(self):
        return u'%s' % self.title
    
    subject = models.ForeignKey(Subject)
    title = models.CharField(blank=False, max_length=100)
    description = models.TextField(blank=True)
    tags = TagField(max_length=400)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)

class Exercise(models.Model):
    
    def __unicode__(self):
        return u'%s' % self.title
    
    title = models.CharField(blank=True, max_length=100)
    description = models.TextField(blank=True)
    tags = TagField(max_length=400)
    # metadata information
    created = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now_add=True)
    updated = models.DateTimeField(blank=True, default=datetime.datetime.now, auto_now=True)    

# tagging conf
tagging.register(Activity, tag_descriptor_attr="tag_handler")
tagging.register(Exercise, tag_descriptor_attr="tag_handler")

dudalibrary/templates/default/search/search.html
{% extends 'base.html' %}
{% load i18n %}
{% load highlight %}

{% block content %}

<h2>{% blocktrans with in_page_total_count=page.object_list|length total_count=paginator.count %}
    Showing {{in_page_total_count}} results out of {{total_count}} found items.{% endblocktrans %}</h2>
    <h2>{% trans "Search" %}</h2>

    <form method="get" action="." class="form-horizontal">
            {{ form.as_table }}
            <input type="submit" value="Search" class="btn">
    </form>
    {% if query %}
        <h3>{% trans "Results" %}</h3>
            {% for result in page.object_list %}
            <hr />
            <div class="row-fluid">
                {% if result.content_type == "resources.resource" %}
                <div class="span2">
                    <div class="resource_list_thumb" id="thumbnail-{{result.object.id}}">            
                        <div class="resource_list_thumb" id="thumbnail-{{result.object.id}}">
	
                            {% for thumb in result.object.thumbnails_path %}
                            {% if forloop.first %}
                            <a href="{{ result.object.get_absolute_url }}?q={{query}}">
                                <img src="{{thumb}}" class="imagedropshadow" />
                            </a>
                            {% if "video" in result.object.category_code_set%}
                            <div class="">
                                <span class="label">{{result.object.humanized_duration}}</span>
                            </div>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="span10">
                  	<div id="information-{{result.object.id}}" class="information">
                  		<p class="title">{% trans "Resource" %}: <a href="{{result.object.get_absolute_url}}?q={{query}}" >{{result.object.title}}</a></p>
                        {% if result.object.description %}
                  		<p class="description"><span class="label label-info">{% trans "Description" %}</span> <span
                  			 class="text">
                             {% highlight_truncate result.object.description with query as desc %}
                            {% if query %}
                            {{desc}}
                  			{% else %}
                  				{{result.object.description}}
                  			{% endif %}
                  			</span></p>
                            {% endif %}
                            {% if result.object.category.all %}
                  		<p class="categories"><span class="label label-info">{%trans "Categories" %}</span> {{result.object.category.all|join:","}}</p>

                        {% endif %}
                  	</div>
                </div>
                {% endif %}
                
                {% if result.content_type == "curricular.activity" %}
                <div class="span2">
                    <a href="{{ result.object.get_absolute_url }}?q={{query}}"><img src="/media/img/icons/folder.png" class="button" alt=""></a>
                </div>
                
                <div class="span10">
                    <h2>{% trans "Activity" %}</h2>
                    <h3>{{result.object}}</h3>
                    <p>{% trans "Items" %}</p>
                    <ul>{% for item in result.object.activityitem_set.all %}
                        <li><a href="{{ result.object.get_absolute_url }}?q={{query}}">{{item}}</a></li>
                        {% endfor%}
                    </ul>
                    
                </div>
                
                {% endif %}

            </div>

                
            {% empty %}
                <p>{% trans "No results found." %}</p>
            {% endfor %}

            {% include "paginator.html" with page_obj=page paginator=page.paginator %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}

{% endblock %}